export const cursors = [
    { title: "Auto", classname: "cursor-auto" },
    { title: "Default", classname: "cursor-default" },
    { title: "Pointer", classname: "cursor-pointer" },
    { title: "Wait", classname: "cursor-wait" },
    { title: "Text", classname: "cursor-text" },
    { title: "Move", classname: "cursor-move" },
    { title: "Help", classname: "cursor-help" },
    { title: "Not Allowed", classname: "cursor-not-allowed" },
    { title: "None", classname: "cursor-none" },
    { title: "Context Menu", classname: "cursor-context-menu" },
    { title: "Progress", classname: "cursor-progress" },
    { title: "Cell", classname: "cursor-cell" },
    { title: "Crosshair", classname: "cursor-crosshair" },
    { title: "Vertical Text", classname: "cursor-vertical-text" },
    { title: "Alias", classname: "cursor-alias" },
    { title: "Copy", classname: "cursor-copy" },
    { title: "No Drop", classname: "cursor-no-drop" },
    { title: "Grab", classname: "cursor-grab" },
    { title: "Grabbing", classname: "cursor-grabbing" },
    { title: "All Scroll", classname: "cursor-all-scroll" },
    { title: "Col Resize", classname: "cursor-col-resize" },
    { title: "Row Resize", classname: "cursor-row-resize" },
    { title: "North Resize", classname: "cursor-n-resize" },
    { title: "East Resize", classname: "cursor-e-resize" },
    { title: "South Resize", classname: "cursor-s-resize" },
    { title: "West Resize", classname: "cursor-w-resize" },
    { title: "North East Resize", classname: "cursor-ne-resize" },
    { title: "North West Resize", classname: "cursor-nw-resize" },
    { title: "South East Resize", classname: "cursor-se-resize" },
    { title: "South West Resize", classname: "cursor-sw-resize" },
    { title: "East West Resize", classname: "cursor-ew-resize" },
    { title: "North South Resize", classname: "cursor-ns-resize" },
    { title: "NE-SW Resize", classname: "cursor-nesw-resize" },
    { title: "NW-SE Resize", classname: "cursor-nwse-resize" },
    { title: "Zoom In", classname: "cursor-zoom-in" },
    { title: "Zoom Out", classname: "cursor-zoom-out" },
];
